### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by jizumer** [ochentaytres/pollen#3]

**Comment by agonriv** [comment]
Created new android project (using Kotlin languaje, API 16 Android 4.1 Jelly Bean) with empty activity

**Comment by agonriv** [comment]
Created firebase project named OchentaytresPollen (invitations sent as owners to Juan, juan.infante.zumer@gmail.com, and oscar, antonioostras@gmail.com)

Enabled Authentication Service, to authenticate with Google provider
